services:
  app:
    build: .
    ports:
      - "1488:1488"
    depends_on:
      - postgres
    environment:
      - DB_HOST=postgres
      - DB_USER=postgres
      - DB_PASSWORD=negr321
      - DB_NAME=Negri
      - DB_PORT=5432

  postgres:
    image: postgres:16.0
    container_name: db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: db
      POSTGRES_PASSWORD: db1234
      POSTGRES_DB: postgres
    ports:
      - "5455:5432"

volumes:
  postgres-data:


